django_MySQL_weather_database/weather/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^weather/', include('weatherapp.urls')),
    url(r'^arrests/', include('weatherapp.urls_arrests')),
    url(r'^admin/', admin.site.urls)
]

django_MySQL_weather_database/weatherapp/urls.py
from django.conf.urls import url

from . import views

app_name = 'weatherapp'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^result', views.result, name='result'),
    url(r'^singleResult', views.singleResult, name='singleResult'),
    url(r'^searchByWeatherType', views.searchByWeatherType, name='searchByWeatherType'),
    url(r'^weatherTypeResponse', views.weatherTypeResponse, name='weatherTypeResponse'),
    url(r'^arrests', views.arrestDisplay, name='arrest_display_url')
]

django_MySQL_weather_database/weatherapp/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models


class Precip(models.Model):
    id = models.IntegerField(db_column='ID', primary_key=True)  # Field name made lowercase.
    precipitation = models.DecimalField(db_column='Precipitation', max_digits=10, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    snowdepth = models.DecimalField(db_column='SnowDepth', max_digits=10, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    snowfall = models.DecimalField(db_column='SnowFall', max_digits=10, decimal_places=2, blank=True, null=True)  # Field name made lowercase.

    def __str__(self):
        return self.id

    class Meta:
        managed = False
        db_table = 'precip'


class Severe(models.Model):
    id = models.IntegerField(db_column='ID', primary_key=True)  # Field name made lowercase.
    blowingsnow = models.IntegerField(db_column='BlowingSnow', blank=True, null=True)  # Field name made lowercase.
    drizzle = models.IntegerField(db_column='Drizzle', blank=True, null=True)  # Field name made lowercase.
    dust_ash = models.IntegerField(db_column='Dust_Ash', blank=True, null=True)  # Field name made lowercase.
    fog = models.IntegerField(db_column='Fog', blank=True, null=True)  # Field name made lowercase.
    freezingdrizzle = models.IntegerField(db_column='FreezingDrizzle', blank=True, null=True)  # Field name made lowercase.
    freezingrain = models.IntegerField(db_column='FreezingRain', blank=True, null=True)  # Field name made lowercase.
    glaze_rime = models.IntegerField(db_column='Glaze_Rime', blank=True, null=True)  # Field name made lowercase.
    groundfog = models.IntegerField(db_column='GroundFog', blank=True, null=True)  # Field name made lowercase.
    hail = models.IntegerField(db_column='Hail', blank=True, null=True)  # Field name made lowercase.
    heavyfog = models.IntegerField(db_column='HeavyFog', blank=True, null=True)  # Field name made lowercase.
    highwinds = models.IntegerField(db_column='HighWinds', blank=True, null=True)  # Field name made lowercase.
    icefog = models.IntegerField(db_column='IceFog', blank=True, null=True)  # Field name made lowercase.
    sleet = models.IntegerField(db_column='Sleet', blank=True, null=True)  # Field name made lowercase.
    mist = models.IntegerField(db_column='Mist', blank=True, null=True)  # Field name made lowercase.
    rain = models.IntegerField(db_column='Rain', blank=True, null=True)  # Field name made lowercase.
    smokehaze = models.IntegerField(db_column='SmokeHaze', blank=True, null=True)  # Field name made lowercase.
    snow = models.IntegerField(db_column='Snow', blank=True, null=True)  # Field name made lowercase.
    thunder = models.IntegerField(db_column='Thunder', blank=True, null=True)  # Field name made lowercase.
    tornado = models.IntegerField(db_column='Tornado', blank=True, null=True)  # Field name made lowercase.

    def __str__(self):
        return str(self.id)

    class Meta:
        managed = False
        db_table = 'severe'


class Temp(models.Model):
    id = models.IntegerField(db_column='ID', primary_key=True)  # Field name made lowercase.
    tavg = models.DecimalField(db_column='TAVG', max_digits=10, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    tmax = models.DecimalField(db_column='TMAX', max_digits=10, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    tmin = models.DecimalField(db_column='TMIN', max_digits=10, decimal_places=2, blank=True, null=True)  # Field name made lowercase.

    def __str__(self):
        return str(self.id)

    class Meta:
        managed = False
        db_table = 'temp'


class WeatherDates(models.Model):
    id = models.IntegerField(primary_key=True)
    month = models.IntegerField(blank=True, null=True)
    day = models.IntegerField(blank=True, null=True)
    year = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return str(self.id)

    class Meta:
        managed = False
        db_table = 'weather_dates'


class Wind(models.Model):
    id = models.IntegerField(db_column='ID', primary_key=True)  # Field name made lowercase.
    averagewindspeed = models.DecimalField(db_column='AverageWindSpeed', max_digits=10, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    wsfg = models.DecimalField(db_column='WSFG', max_digits=10, decimal_places=2, blank=True, null=True)  # Field name made lowercase.

    def __str__(self):
        return str(self.id)

    class Meta:
        managed = False
        db_table = 'wind'

django_MySQL_weather_database/weatherapp/views.py
from django.shortcuts import get_object_or_404, render

from .models import Temp, WeatherDates, Precip, Severe
import datetime

def index(request):
    date = datetime.date.today()
    month = date.month
    day = date.day
    context = {
        'current_month': month,
        'current_day': day,
    }
    return render(request, 'weatherapp/index.html', context)


def result(request):
    form_month = request.POST['month'] #retrieving form results
    form_day = request.POST['day']
    form_year = request.POST['year']

    temperatureResults = temperatureCalculate(form_month, form_day, form_year, False)
    precipResults = precipCalculate(form_month, form_day, form_year, False)
    severeResults = severeCalculate(form_month, form_day, form_year, False)
    severeNames = ("Blowing Snow", "Drizzle", "Dush/Ash","Fog","Freezing Drizzle","Freezing Rain","Glaze/Rime","Ground Fog","Hail","Heavy Fog","High Winds","Ice Fog","Sleet","Mist","Rain","Smoke/Haze","Snow","Thunder","Tornado")

    context = {
        'minimum_temperature': temperatureResults[0],
        'average_temperature': temperatureResults[1],
        'maximum_temperature': temperatureResults[2],
        'precipitation': precipResults[0],
        'snow_depth': precipResults[1],
        'snow_fall': precipResults[2],
        'month': form_month,
        'day': form_day,
        'year': form_year,
        'severe' : severeResults,
        'severeNames' : severeNames,
        'single_bool' : False
    }
    return render(request, 'weatherapp/result.html', context)


def weatherTypeResponse(request):
    form_type = request.POST['select_type']
    form_year = request.POST['year']

    weather_set = Severe.objects.filter(**{form_type: 1})  # get every record where the weather type of interest was detected
    id_set = WeatherDates.objects.filter(id__in=weather_set, year__gte=form_year)

    context={
        'weather_type': form_type,
        'start_year': form_year,
        'id_list': id_set
    }

    return render(request, 'weatherapp/searchByWeatherTypeResult.html', context)


def searchByWeatherType(request):
    return render(request, 'weatherapp/searchByWeatherType.html')


def singleResult(request):
    form_month = request.POST['month']  # retrieving form results
    form_day = request.POST['day']
    form_year = request.POST['year']

    temperatureResults = temperatureCalculate(form_month, form_day, form_year, True)
    precipResults = precipCalculate(form_month, form_day, form_year, True)
    severeResults = severeCalculate(form_month, form_day, form_year, True)
    severeNames = ("Blowing Snow", "Drizzle", "Dush/Ash", "Fog", "Freezing Drizzle", "Freezing Rain", "Glaze/Rime", "Ground Fog", "Hail", "Heavy Fog", "High Winds", "Ice Fog", "Sleet", "Mist", "Rain", "Smoke/Haze", "Snow", "Thunder", "Tornado")


    context={
        'minimum_temperature': temperatureResults[0],
        'average_temperature': temperatureResults[1],
        'maximum_temperature': temperatureResults[2],
        'precipitation': precipResults[0],
        'snow_depth': precipResults[1],
        'snow_fall': precipResults[2],
        'month': form_month,
        'day': form_day,
        'year': form_year,
        'severe' : severeResults,
        'severeNames' : severeNames,
        'single_bool' : True
    }
    for key, value in context.items():
        print(str(key) + "->" + str(value))
    return render(request, 'weatherapp/result.html', context)


def arrestDisplay(request):
    from bs4 import BeautifulSoup
    import urllib.request

    url = "http://mugshots.com/US-Counties/Georgia/Fulton-County-GA/"
    r = urllib.request.urlopen(url)
    soup = BeautifulSoup(r, "html.parser")

    names = soup.find_all("div", class_="label")

    names_list = []

    for name in names:
        names_list.append(name.get_text())

    context = {
        'names_list': names_list,
    }

    return render(request, 'weatherapp/arrestDisplay.html', context)


def temperatureCalculate(inputMonth, inputDay, inputYear, single_bool):

    # single_bool = true if searching for a single date
    if single_bool:
        idSet = WeatherDates.objects.filter(month=inputMonth,
                                            day=inputDay,
                                            year=inputYear)
    else:
        idSet = WeatherDates.objects.filter(month=inputMonth,
                                        day=inputDay,
                                        year__gte=inputYear)  # QuerySet containing pk value of every entry on month/day

    tempSet = Temp.objects.filter(id__in=idSet)  # using idSet to retrieve every Temp object entry for month/day

    minTemp = 0  # running totals of the temperature values
    averageTemp = 0
    maxTemp = 0

    minTempCount = 0  # counts to keep track of how many non-null entries
    averageTempCount = 0
    maxTempCount = 0

    for entry in tempSet:
        if entry.tmin > -1000:  # database uses -9999 as null value.. -1000 is arbitrary number higher than -9999, lower than feasible temp value
            minTemp += entry.tmin
            minTempCount += 1
        if entry.tavg > -1000:
            averageTemp += entry.tavg
            averageTempCount += 1
        if entry.tmax > -1000:
            maxTemp += entry.tmax
            maxTempCount += 1

    if minTempCount == 0:    #preventing division by 0 error, providing more accurate results
        minTemp = "No data"
    else:
        minTemp = round(minTemp/minTempCount, 1)  # average will be equal to the final total, divided by the count

    if averageTempCount ==0:
        averageTemp = "No data"
    else:
        averageTemp = round(averageTemp/averageTempCount, 1)

    if maxTempCount == 0:
        maxTemp = "No data"
    else:
        maxTemp = round(maxTemp/maxTempCount,1)

    return minTemp, averageTemp, maxTemp


def precipCalculate(input_month, input_day, input_year, single_bool):
    if single_bool:
        id_set = WeatherDates.objects.filter(month=input_month,
                                            day=input_day,
                                            year=input_year)
    else:
        id_set = WeatherDates.objects.filter(month=input_month,
                                            day=input_day,
                                            year__gte=input_year)

    precip_set = Precip.objects.filter(id__in=id_set)

    precipitation = 0
    snow_depth = 0
    snow_fall = 0

    precipitation_count = 0
    snow_depth_count = 0
    snow_fall_count = 0

    for entry in precip_set:
        if entry.precipitation > -1000:  # database uses -9999 as null value.. -1000 is arbitrary number higher than -9999, lower than feasible temp value
            precipitation += entry.precipitation
            precipitation_count += 1
        if entry.snowdepth > -1000:
            snow_depth += entry.snowdepth
            snow_depth_count += 1
        if entry.snowfall > -1000:
            snow_fall += entry.snowfall
            snow_fall_count += 1

    if precipitation_count == 0: # preventing division by 0 error, providing more accurate results
        precipitation = "No data"
    else:
        precipitation = round(precipitation/precipitation_count,1)

    if snow_depth_count == 0:
        snow_depth = "No data"
    else:
        snow_depth = round(snow_depth/snow_depth_count,1)

    if snow_fall_count == 0:
        snow_fall = "No data"
    else:
        snow_fall = round(snow_fall/snow_fall_count,1)

    return precipitation, snow_depth, snow_fall


def severeCalculate(inputMonth, inputDay, inputYear, single_bool):
    if single_bool:
        idSet = WeatherDates.objects.filter(month=inputMonth,
                                            day=inputDay,
                                            year=inputYear)
    else:
        idSet = WeatherDates.objects.filter(month=inputMonth,
                                            day=inputDay,
                                            year__gte=inputYear)
    severeSet = Severe.objects.filter(id__in=idSet)

    blowingsnow_count = 0
    drizzle_count = 0
    dust_ash_count = 0
    fog_count = 0
    freezingdrizzle_count = 0
    freezingrain_count = 0
    glaze_rime_count = 0
    groundfog_count = 0
    hail_count = 0
    heavyfog_count = 0
    highwinds_count = 0
    icefog_count = 0
    sleet_count = 0
    mist_count = 0
    rain_count = 0
    smokehaze_count = 0
    snow_count = 0
    thunder_count = 0
    tornado_count = 0

    for entry in severeSet:
        if entry.blowingsnow == 1:
            blowingsnow_count += 1

        if entry.drizzle == 1:
            drizzle_count += 1

        if entry.dust_ash == 1:
            dust_ash_count += 1

        if entry.fog == 1:
            fog_count += 1

        if entry.freezingdrizzle== 1:
            freezingdrizzle_count += 1

        if entry.freezingrain == 1:
            freezingrain_count += 1

        if entry.glaze_rime == 1:
            glaze_rime_count += 1

        if entry.groundfog == 1:
            groundfog_count += 1

        if entry.hail == 1:
            hail_count += 1
        if entry.heavyfog== 1:
            heavyfog_count += 1

        if entry.highwinds == 1:
            highwinds_count += 1

        if entry.icefog == 1:
            icefog_count += 1

        if entry.sleet== 1:
            sleet_count += 1

        if entry.mist== 1:
            mist_count += 1

        if entry.rain == 1:
            rain_count += 1

        if entry.smokehaze == 1:
            smokehaze_count += 1

        if entry.snow == 1:
            snow_count += 1

        if entry.thunder == 1:
            thunder_count += 1

        if entry.tornado == 1:
            tornado_count += 1

    return blowingsnow_count, drizzle_count,dust_ash_count,fog_count,freezingdrizzle_count,freezingrain_count, glaze_rime_count,groundfog_count,hail_count,heavyfog_count,highwinds_count,icefog_count,sleet_count,mist_count,rain_count,smokehaze_count,snow_count,thunder_count,tornado_count

django_MySQL_weather_database/weatherapp/templates/weatherapp/arrestDisplay.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'weatherapp/arrestDisplay.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Recent Arrests</title>
</head>
<body>
    <ul id="navBarUL">
        <li class="navBarItem" style="font-weight:bold"><a href="{% url 'weatherapp:index' %}">Search by Date</a></li>
        <li class="navBarItem" style="font-weight:bold"><a href="{% url 'weatherapp:searchByWeatherType' %}">Search by Weather Type</a></li>
    </ul>

    Recent Arrests in Fulton County:
    <table>
    <tr><td>Name</td></tr>
    {% for name in names_list %}
        <tr>
            <td>
                {{ name }}
            </td>
        </tr>
    {% endfor %}
    </table>
</body>
</html>

django_MySQL_weather_database/weatherapp/templates/weatherapp/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'weatherapp/index.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search By Date</title>
</head>
<body>
    <ul id="navBarUL">
        <li class="navBarItem" style="font-weight:bold"><a href="{% url 'weatherapp:index' %}">Search by Date</a></li>
        <li class="navBarItem" style="font-weight:bold"><a href="{% url 'weatherapp:searchByWeatherType' %}">Search by Weather Type</a></li>
    </ul>
    <div id="form1">
        <form action="{% url 'weatherapp:result'  %}" method="post">
            {% csrf_token %}
            Month:
            <input type="number" name="month" min="1" max="12" value="{{ current_month }}">
            Day:
            <input type="number" name="day" min="1" max="31" value="{{ current_day }}">
            Starting Year (1930-2015):
            <input type="number" name="year" min="1930" max="2015" value="1930">
            <br>
            <input type="submit" value="Calculate" />
        </form>
    </div>

    <div id="form2">
        <form action="{% url 'weatherapp:singleResult'  %}" method="post">
            {% csrf_token %}
            Month:
            <input type="number" name="month" min="1" max="12" value="{{ current_month }}">
            Day:
            <input type="number" name="day" min="1" max="31" value="{{ current_day }}">
            Year (1930-2015):
            <input type="number" name="year" min="1930" max="2015" value="1930">
            <br>
            <input type="submit" value="Calculate" />
        </form>
    </div>


</body>
</html>

django_MySQL_weather_database/weatherapp/templates/weatherapp/result.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'weatherapp/result.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Result</title>
</head>
<body>

    <ul id="navBarUL">
        <li class="navBarItem" style="font-weight:bold"><a href="{% url 'weatherapp:index' %}">Search by Date</a></li>
        <li class="navBarItem" style="font-weight:bold"><a href="{% url 'weatherapp:searchByWeatherType' %}">Search by Weather Type</a></li>
    </ul>

    <h1>Historical Weather Data For {{ month }}/{{ day }} </h1>
    {% if single_bool %}
        <h2>For the year {{ year }}</h2>
    {% else %}
        <h2>Since {{ year }}</h2>
    {% endif %}

    <table>
        <tr>
            <td id="emptyCell"></td>
            <th class="centeredHeader">Data</th>
            <th class="centeredHeader">Unit</th>
        </tr>
        <tr>
            <th>
                Minimum Temperature
            </th>
            <td>
                {{ minimum_temperature }}
            </td>
            <td>
                (F)
            </td>
        </tr>
        <tr>
            <th>
                Average Temperature
            </th>
            <td>
                {{ average_temperature }}
            </td>
            <td>
                (F)
            </td>
        </tr>
        <tr>
            <th>
                Maximum Temperature
            </th>
            <td>
                {{ maximum_temperature }}
            </td>
            <td>
                (F)
            </td>
        </tr>

        <tr>
            <td class="tdDivider"></td>
            <td class="tdDivider"></td>
            <td class="tdDivider"></td>
        </tr>

        <tr>
            <th>
                Rainfall
            </th>
            <td>
                {{ precipitation }}
            </td>
            <td>
                Inches
            </td>
        </tr>
        <tr>
            <th>
                Snow Depth
            </th>
            <td>
                {{ snow_depth }}
            </td>
            <td>
                Inches
            </td>
        </tr>
        <tr>
            <th>
                Snowfall
            </th>
            <td>
                {{ snow_fall }}
            </td>
            <td>
                Inches
            </td>
        </tr>
    </table>

    <table>
        <tr>
            <th class="centeredHeader">
                Type
            </th>
            <th class="centeredHeader">
                Value
            </th>
        </tr>
        {% for value in severe %}
            {% for name in severeNames %}
                {% if forloop.counter == forloop.parentloop.counter %}
                    <tr>
                        <td>
                            {{ name }}
                        </td>
                        <td>
                            {{ value }}
                        </td>
                {% endif %}
            </tr>
            {% endfor %}
        {% endfor %}
    </table>
</body>
</html>

django_MySQL_weather_database/weatherapp/templates/weatherapp/searchByWeatherType.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'weatherapp/index.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search By Weather Type</title>
</head>
<body>
    <ul id="navBarUL">
        <li class="navBarItem" style="font-weight:bold"><a href="{% url 'weatherapp:index' %}">Search by Date</a></li>
        <li class="navBarItem" style="font-weight:bold"><a href="{% url 'weatherapp:searchByWeatherType' %}">Search by Weather Type</a></li>
    </ul>

    <form action="{% url 'weatherapp:weatherTypeResponse' %}" method="post">
        {% csrf_token %}
        Starting Year (1930-2015):
        <input type="number" name="year" min="1930" max="2015" value="1930">
        <select name="select_type">
            <option value="blowingsnow">Blowing Snow</option>
            <option value="drizzle">Drizzle</option>
            <option value="dust_ash">Dust/Ash</option>
            <option value="fog">Fog</option>
            <option value="freezingdrizzle">Freezing Drizzle</option>
            <option value="freezingrain">Freezing Rain</option>
            <option value="glaze_rime">Glaze/Rime</option>
            <option value="groundfog">Ground Fog</option>
            <option value="hail">Hail</option>
            <option value="heavyfog">Heavy Fog</option>
            <option value="highwinds">High Winds</option>
            <option value="icefog">Ice Fog</option>
            <option value="sleet">Sleet</option>
            <option value="mist">Mist</option>
            <option value="rain">Rain</option>
            <option value="smokehaze">Smoke/Haze</option>
            <option value="snow">Snow</option>
            <option value="thunder">Thunder</option>
            <option value="tornado">Tornado</option>
        </select>
        <!--option names correspond to model fields-->
        <br><br>
        <input type="submit" value="Submit"/>
    </form>
</body>
</html>

django_MySQL_weather_database/weatherapp/templates/weatherapp/searchByWeatherTypeResult.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'weatherapp/result.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search By Type - Results</title>
</head>
<body>
    <ul id="navBarUL">
        <li class="navBarItem" style="font-weight:bold"><a href="{% url 'weatherapp:index' %}">Search by Date</a></li>
        <li class="navBarItem" style="font-weight:bold"><a href="{% url 'weatherapp:searchByWeatherType' %}">Search by Weather Type</a></li>
    </ul>

    <h1>Results of Search for {{ weather_type }}</h1>
    <h2>Since {{ start_year }}</h2>

    <table>
        <tr>
            <th>Month</th>
            <th>Day</th>
            <th>Year</th>
        </tr>
        {% for entry in id_list %}
            <tr>
                <td>{{ entry.month }}</td>
                <td>{{ entry.day }}</td>
                <td>{{ entry.year }}</td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>